# -*- coding: utf-8 -*-
"""Arrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sXr3bzl8E4mkgadWv6vJXCW2ZsxLdtD7

<h4>1.Let us say your expense for every month are listed below.</h4>
"""

#expense for each month jan - may
expenses = [2200, 2350, 2600, 2130, 2190]

"""1. In Feb, how many dollars you spent extra compare to January?
2. Find out your total expense in first quarter (first three months) of the year.
3. Find out if you spent exactly 2000 dollars in any month
4. June month just finished and your expense is 1980 dollar. Add this item to our monthly expense list
5. You returned an item that you bought in a month of April and
got a refund of 200$. Make a correction to your monthly expense list
based on this
"""

#1
feb_extra_comp_jan = expenses[1]-expenses[0]
print(f"Extra $ spent in feb compared to jan : {feb_extra_comp_jan}")

#2
total_spent_Q1 = expenses[0]+expenses[1]+expenses[2]
print(f"Total spent in first quarter: {total_spent_Q1}")

#3
months_2000 = []
for i in expenses:
    if i == 2000:
        months_2000.append(expenses.index(i))
if len(months_2000) == 0:
    print("There is not a single month which met the $2000 mark.")
else:
    print(f"Months with expenses greater than or equal to 2000 : {months_2000} month(s).")

#4
expenses.insert(6,1980)
print(f'expenses:{expenses}')

#5
expenses[3] = expenses[3]  - 200 
print(f'expenses:{expenses}')

"""----

<h4>2.You have a list of your favourite marvel super heros.</h4>

heros=['spider man','thor','hulk','iron man','captain america']

1. Length of the list
2. Add 'black panther' at the end of this list
3. You realize that you need to add 'black panther' after 'hulk',
   so remove it from the list first and then add it after 'hulk'
4. Now you don't like thor and hulk because they get angry easily :)
   So you want to remove thor and hulk from list and replace them with doctor strange (because he is cool).
   Do that with one line of code.
5. Sort the heros list in alphabetical order (Hint. Use dir() functions to list down all functions available in list)
"""

heros=['spider man','thor','hulk','iron man','captain america']

#1
print(f"Total heros: {len(heros)}")

#2
heros.append('black panther')
heros

#3
#remove black panther
heros.remove('black panther')
#adding black panther after hulk
heros.insert(3, 'black panther')
heros

#4
heros[1:3] = ['doctor strange']
heros

#5
heros.sort()
heros

"""<h4>3.Create a list of all odd numbers between 1 and a max number. Max number is something you need to take from a user using input() function</h4>"""

max_number = int(input('Enter the upper limit of odd numbers list: '))
odd = []
for i in range(max_number+1):
    if i%2 != 0:
        odd.append(i)
print(f'odd numbers less than {max_number}: {odd}')

